
public class Parent extends Person{

    Parent()
    {
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
        System.out.println("Parent");
    }
}